[theme]
primaryColor = "#6366f1"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e2e8f0"
font = "sans serif"

[client]
showErrorDetails = true

[server]
maxUploadSize = 200
enableXsrfProtection = true